class ApiEndPoints {
  static const String post_api_Login = "login";
  static const String post_api_socialLogin = "socialLogin";
  static const String post_api_Register = "register";
  static const String post_api_forgotPassword = "forgotpassword";
  static const String post_api_ChangePassword = "changePassword";
  static const String post_api_uploadImage_document = "uploadUserImage";
  static const String update_username = "updateProfile";
  static const String callCenter = "callCenter";
  static const String getCategory = "getCategory";
  static const String saveUserCategory = "saveUserCategory";
  static const String addCard = "addCard";
  static const String getCards = "getCards";
  static const String deleteCard = "deleteCard";
  static const String post_api_home = "getHomePage";
  static const String post_api_getRoom = "getRoom";
  static const String post_api_checkRoomAvailability= "checkRoomAvailability";
  static const String post_api_GetHotelByCategory = "getHotelByCategory";
  static const String post_api_GetRecommendedHotels = "getRecommendedHotels";
  static const String post_api_GotHotelByLocation = "getHotelByLocation";
  static const String post_api_create_booking = "createBooking";
  static const String post_api_get_booking = "getBooking";
  static const String post_api_discoverNewPlaces = "discoverNewPlaces";
  static const String post_api_addReview = "addReview";
  static const String post_api_search_hotel = "searchHotel";
  static const String post_api_getTags = "getTags";
  static const String post_api_cancelBooking = "cancelBooking";
  static const String post_api_getHotelMap = "getHotelMap";
}
