name: book_it
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.

  cupertino_icons: ^1.0.0
  shimmer: ^1.0.0
  transparent_image: ^0.1.0
  flutter_slidable: ^0.4.9
  carousel_pro: ^1.0.0
  simple_animations: ^1.3.3
  like_button: ^0.1.9
  percent_indicator: ^1.0.15
  flutter_rating: ^0.0.2
  giffy_dialog: ^1.3.0
  flutter_credit_card:
  google_maps_flutter: ^0.5.27+1
  shared_preferences:
  cloud_firestore: ^0.12.7
  firebase_auth: ^0.11.1+10
  firebase_storage:
  firebase_database: ^3.0.4
  firebase_core:
  firebase_messaging:
  image_picker:
  url_launcher: ^5.7.10
  carousel_slider: ^2.0.0
  flutter_dialogflow: ^0.1.2
  date_time_picker: ^1.1.1
  date_format: ^1.0.9
  flat_icons_flutter: ^1.0.2
  flutter_svg:
  flutter_bloc:
  http:
  bloc:
  rxdart:
  dio:
  image_cropper:         #IMAGE CROPPER
  permission_handler:
  stripe_payment:
  dot_navigation_bar:
  paged_vertical_calendar:
  flutter_webview_plugin:
#  table_calendar: ^2.3.3
#  calendar_views: ^0.5.2
#  vertical_calendar: ^1.0.1+6
#  paged_vertical_calendar:
#  simple_vertical_calendar:


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.8.0"

flutter_icons:
  android: true
  ios: true
  image_path: "assets/image/logo/bLogo.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  fonts:
    - family: Sans
      fonts:
        - asset: assets/font/OpenSans-Semibold.ttf
          weight: 600
        - asset: assets/font/OpenSans-Regular.ttf
          weight: 400
        - asset: assets/font/OpenSans-Light.ttf
          weight: 200
    - family: One
      fonts:
        - asset: assets/font/HaveHeartOne.ttf
          weight: 400
    - family: Berlin
      fonts:
        - asset: assets/font/berlin.TTF
          weight: 600
    - family: Gotik
      fonts:
        - asset: assets/font/GOTHIC.TTF
          weight: 300
        - asset: assets/font/gotik.TTF
          weight: 600
    - family: Amira
      fonts:
        - asset: assets/font/Amira.otf
          weight: 500
    - family: Sofia
      fonts:
        - asset: assets/font/Sofia/SofiaProBold.otf
          weight: 900
        - asset: assets/font/Sofia/SofiaProSemiBold.otf
          weight: 800
        - asset: assets/font/Sofia/SofiaProMedium.otf
          weight: 700
        - asset: assets/font/Sofia/SofiaProRegular.otf
          weight: 600
        - asset: assets/font/Sofia/SofiaProLight.otf
          weight: 500
        - asset: assets/font/Sofia/SofiaProExtraLight.otf
          weight: 400
        - asset: assets/font/Sofia/SofiaProUltraLight.otf
          weight: 300
    - family: category
      fonts:
        - asset: assets/custom_icon/ic_category.ttf
    - family: message
      fonts:
        - asset: assets/custom_icon/ic_message.ttf
    - family: trip
      fonts:
        - asset: assets/custom_icon/ic_trip.ttf
    - family: file
      fonts:
        - asset: assets/custom_icon/ic_file.ttf
    - family: hearth
      fonts:
        - asset: assets/custom_icon/ic_hearth.ttf
    - family: home
      fonts:
        - asset: assets/custom_icon/ic_home.ttf
    - family: profile
      fonts:
        - asset: assets/custom_icon/ic_profile.ttf
    - family: ReservationIcon
      fonts:
        - asset: assets/custom_icon/ReservationIcon.ttf
    - family: Ic_reservation
      fonts:
        - asset: assets/custom_icon/Ic_reservation.ttf


  assets:
    - assets/credentials.json
    - assets/map_style/map_style.txt
    #    - assets/image/onBoardingImage/onBoarding1.png
    #    - assets/image/onBoardingImage/onBoarding2.png
    #    - assets/image/onBoardingImage/onBoarding3.png
    - assets/image/icon/fbIcon.png
    - assets/image/icon/googleIcon.png
    - assets/image/icon/amerika.png
    - assets/image/icon/paris.png
    - assets/image/icon/england.png
    - assets/image/icon/italia.png
    - assets/image/icon/spanyol.png
    - assets/image/icon/marker.png
    - assets/image/icon/thailand.png
    - assets/image/icon/twitterIcon.png
    - assets/image/icon/food.png
    - assets/image/images/GirlProfile.png
    #    - assets/image/homeImage/experience.png
    #    - assets/image/homeImage/home.png
    #    - assets/image/homeImage/hotel.png
    #    - assets/image/homeImage/travel.png
    - assets/image/images/bannerProfile.png
    - assets/image/images/map.png
    - assets/image/images/search.png
    - assets/image/illustration/message.png
    - assets/image/illustration/girlcallcenter.png
    - assets/image/destinationPopuler/destination1.png
    #    - assets/image/destinationPopuler/destination4.jpg
    #    - assets/image/destinationPopuler/destination5.jpg
    #    - assets/image/destinationPopuler/populer2.png
    - assets/image/destinationPopuler/tripBackground.png
    - assets/image/illustration/social.png
    - assets/image/illustration/noMessage.png
    - assets/image/illustration/peopleChat.png
    - assets/image/illustration/empty.png
    - assets/image/icon/box.png
    - assets/image/icon/logo1.png
    - assets/image/icon/logo2.png
    - assets/image/icon/logo3.png
    - assets/image/icon/logo4.png
    - assets/image/icon/wifi.png
    - assets/image/icon/monitor.png
    - assets/image/icon/swimming.png
    - assets/image/icon/clean.png
    - assets/image/icon/notification.png
    - assets/image/icon/callCenter.png
    - assets/image/icon/card.png
    - assets/image/icon/coupon.png
    - assets/image/icon/settings.png
    - assets/image/icon/profile.png
    - assets/image/icon/confetti.png
    - assets/image/icon/sneaker.png
    - assets/image/icon/lamp.png
    - assets/image/icon/plant.png
    - assets/image/icon/bag.png
    - assets/image/icon/tour.png
    - assets/image/icon/playground.png
    - assets/image/icon/ticket.png
    - assets/image/logo/logo.png
    - assets/image/logo/fullLogo.png
    - assets/image/logo/bLogo.png
    - assets/video/onBoarding.gif
    - assets/image/illustration/messageIlustration.png
    - assets/image/images/calendar.svg
    - assets/image/images/edit.svg
    - assets/image/images/location.svg
    - assets/image/images/location_blue.svg
    - assets/image/images/profile.svg
    - assets/image/images/tick.svg
    - assets/image/images/card.png
    - assets/image/images/visa.png
    - assets/image/images/master_card.svg
    - assets/image/images/card_bg.svg
    - assets/image/icon/bookings.svg
    - assets/image/icon/chat.svg
    - assets/image/icon/travel.svg
    - assets/image/icon/heart.svg
    - assets/image/icon/home.svg
    - assets/image/icon/profile.svg
    - assets/image/onBoardingImage/B1.png
    - assets/image/onBoardingImage/G1.png
    - assets/image/onBoardingImage/N1.png
    - assets/image/destinationPopuler/vacations_placeholder.svg
    - assets/image/destinationPopuler/vacation.png
    - assets/image/images/tick_b.svg
    - assets/image/images/update_location1.svg
    - assets/image/images/update_location2.svg
    - assets/image/images/privacy_policy.svg
    - assets/image/images/terms.svg




  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
